version: "3.9"

services:
  mysql:
    image: mysql:8.0.33
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --innodb-use-native-aio=0 
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./config:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    ports:
      - "3007"
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3307
    networks:
      - netnode

  node:
    build:
      context: ./node_app
    container_name: node
    entrypoint: dockerize -wait tcp://mysql:3307 -timeout 20s docker-entrypoint.sh npm start
    tty: true
    environment:
      - EXPRESS_SERVER_PORT=3000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_SCHEMA=nodedb
      - DB_PORT=3307
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - netnode

  nginx:
    build: 
      context: ./nginx
    entrypoint: dockerize -wait tcp://node:3000 -timeout 20s /docker-entrypoint.sh nginx -g "daemon off;"
    container_name: nginx
    networks: 
      - netnode
    ports: 
      - "8080:80"
    depends_on:
      - node

networks:
  netnode: